### PR TITLE
#15927: ODQ paywall

### PR DESCRIPTION
**Pull request by aabellagm**
Added event for ODQ Paywall
Show a message informing about the current paywall state and control new error executing commands.

### CODE REVIEW

**Comment by hgfkncdjnv** [comment]
هلوو

**Comment by hgfkncdjnv** [comment]
2391

**Comment by hgfkncdjnv** [comment]
تغير الملف

**Comment by hgfkncdjnv** [comment]
موجه غضب JohnMcPMS:addmissingexport

**Review by Maik1985Hansel — APPROVED** [review]

**Pull request closed without merging**
